import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function handleSignUpButtonClick() {}

function handleSignInButtonClick() {}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans antialiased`}
      >
        <nav className="w-screen h-16 border-b border-b-zinc-600 flex justify-between items-center px-8" id="page-header">
          <div>
            <h2>logo</h2>
          </div>
          <div>
            <button>Search</button>
          </div>
          <div>
            <a className="mr-1 p-2.5 py-1.5 rounded border border-zinc-400" href="/signin">Sign in</a>
            <a className="ml-1 p-2.5 py-1.5 rounded bg-white text-black" href="/signup">Sign up</a>
          </div>
        </nav>
        {children}
        {/*<footer id="page-footer" className="w-screen flex items-center justify-center pb-16 pt-8 border-t border-t-zinc-600">
          copyright 2025 me
        </footer>*/}
      </body>
    </html>
  );
}
